language: python
python:
- 3.6
install:
- pip install codecov
- pip install -U tox-travis
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davidemoro
  password:
    secure: Oz9zy07OUGfcl6fFEAz7GPms3oT7aAeLONI78H58SYbeVJ2N6gz2brU0znxgjq+i5c+FhdwdcbNRcAJy1s/WARAnfKxBUN7pm9fw9urGvpEGT/CJASWlwRPqSQFgBoVDZ174U/iE//FsCbgRBOqIDgHuJaA7JzcPfGFu/bPZNrF2d0IKCgXFhB3NZwauEs0P8odhxl+kVxCB4vvszj9DSUFcNkD3/rBHlc6PGjL/LcMLO5HWkRvZKkFP64Fu+Cs3/UyLzFIRMZ4sIPEmntytfqYQ3F1spYt3sfxXOMc5AI0uUvAhwa0TLx9800JLTRsTbyL66OxCaFQ7tZ2SDHf4LR2Lber6ohkVwsZwsF9UfhtvP7+ajqqzWZA7++1XHACMGLB8oN2kyBcNr7wtCwB9gDjt0xNrz+9Vj97yfqZo5rI9fQnnX/grHmVcuZCnpcl5lfiVg+0eh0gjXWVngsda4jF+zTgrACmLsXj5JawSJZsje6aNl88BE0SdUy5UdbyAFEYmrmsQUFol9MRVRJv4B6OwJvEloJrG9XtCmIlRjbGvs+Wz+OH/sd0XFooYg4/x2Y4VDiyHUtdeR02SS8j2fdySgxaZgqPvNE+A0vgErtrJXhohlWJSor905eQId9vsw0UUKHUG7w8JaxS/eblac1P6wtboPpKILmgR3plyDrU=
  on:
    tags: true
    repo: davidemoro/play_websocket
    python: 3.6
